config/routes.rb
Rails.application.routes.draw do
  resources :invests
  #get "/g" => 'invests#week_glist'
  ## works OK ## match '/charts/week_glist(.:format)' => 'charts#week_glist', :via => :get  , :as => 'charts_week_glist'
  match '/charts/glist/:user/:part(.:format)' => 'charts#glist', :via => :get  , :as => 'charts_glist'
  #url_requests GET    /urls/:url_id/requests(.:format)          requests#index
  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/invest.rb
class Invest < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
require 'securerandom'

class User < ActiveRecord::Base
  before_create :set_auth_token


  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  private
    def set_auth_token
      return if auth_token.present?
      self.auth_token = generate_auth_token
    end
    def generate_auth_token
      SecureRandom.uuid.gsub(/\-/,'')
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token, if: :json_request?
  before_filter :configure_permitted_parameters, if: :devise_controller?



  private
  def json_request?
    request.format.json?
  end
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

end

app/controllers/charts_controller.rb
require 'date'

class BigDecimal
  def as_json(options = nil) #:nodoc:
    if finite?
      self
    else
      NilClass::AS_JSON
    end
  end
end
class ChartsController < ApplicationController
  def glist
     part = params[:part]
     @current_user = User.find_by_id(params[:user])
    if(part.match(/week/))
      return week_glist
    elsif(part.match(/month/))
      return month_glist
    elsif(part.match(/year/))
      return year_glist
    end
  end
  def week_glist
    res = {}
    res2 = []
    Invest.where("user_id = ? and date(created_at) >= ?",@current_user,Date.today-1.week).group("name,date(created_at)").pluck("date(created_at) as created_at, amount, name").map do |n,v,a|
        res[a] = Array.new() if res[a].nil?
        #logger.debug("got #{Date.parse(n.to_s).to_time.to_i}")
        #res[a] << [n,v.to_f]
        res[a] << [ (Date.parse(n.to_s).to_time.to_i * 1000),v.to_f]
   end
   res.each_pair{|k,v| res2<< {"name": k, data: v}}
   render json: res2
  end

  def year_glist
    res = {}
    res2 = []
    Invest.where("user_id = ? and date(created_at) >= ?",@current_user,Date.today-1.year).group("name,created_at").pluck("date(created_at) as created_at, amount, name").map do |n,v,a|
        res[a] = Array.new() if res[a].nil?
        #res[a] << [n,v]
        res[a] << [ (Date.parse(n.to_s).to_time.to_i * 1000),v.to_f]
   end
   res.each_pair{|k,v| res2<<{name: k, data: v}}
   render json: res2
  end

  def month_glist
    res = {}
    res2 = []
    Invest.where("user_id = ? and date(created_at) >= ?",@current_user,Date.today-1.month).group("name,created_at").pluck("date(created_at) as created_at, amount, name").map do |n,v,a|
        res[a] = Array.new() if res[a].nil?
        #res[a] << [n,v]
        res[a] << [ (Date.parse(n.to_s).to_time.to_i * 1000),v.to_f]
   end
   res.each_pair{|k,v| res2<<{name: k, data: v}}
   render json: res2
  end
end

app/controllers/invests_controller.rb
include ActionController::HttpAuthentication::Token::ControllerMethods

class InvestsController < ApplicationController
  before_action :authenticate
  #before_action :authenticate_user!
  before_action :set_invest, only: [:show, :edit, :update, :destroy]

  # GET /invests
  # GET /invests.json
  def index
    #@current_user = current_user if current_user
    if current_user
      @current_user = current_user
    else
      #@current_user = anon_user
    end
    #logger.debug "898qqq I got #{@current_user}"
    @invests = Invest.all
  end

  # GET /invests/1
  # GET /invests/1.json
  def show
    #logger.debug "qqq I got #{current_user}"
  end

  # GET /invests/new
  def new
    @invest = Invest.new
  end

  # GET /invests/1/edit
  def edit
  end

  # POST /invests
  # POST /invests.json
  def create
    @invest = Invest.new(invest_params)
    @current_user = current_user if current_user
    @invest.user = @current_user if @current_user
    respond_to do |format|
      if @invest.save
        format.html { redirect_to @invest, notice: 'Invest was successfully created.' }
        format.json { render :show, status: :created, location: @invest }
      else
        format.html { render :new }
        format.json { render json: @invest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invests/1
  # PATCH/PUT /invests/1.json
  def update
    respond_to do |format|
      if @invest.update(invest_params)
        format.html { redirect_to @invest, notice: 'Invest was successfully updated.' }
        format.json { render :show, status: :ok, location: @invest }
      else
        format.html { render :edit }
        format.json { render json: @invest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invests/1
  # DELETE /invests/1.json
  def destroy
    @invest.destroy
    respond_to do |format|
      format.html { redirect_to invests_url, notice: 'Invest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def authenticate
      if request.format.json?
        authenticate_or_request_with_http_token do |token,options|
          @current_user = User.find_by(auth_token: token)
          @current_user
        end
      else
        authenticate_user!
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_invest
      @invest = Invest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invest_params
      params.require(:invest).permit(:user_id, :bank, :name, :amount)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invests_helper.rb
module InvestsHelper
end

app/views/invests/_form.html.erb
<%= simple_form_for(@invest) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.input :bank %>
    <%= f.input :name %>
    <%= f.input :amount %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/invests/edit.html.erb
<h1>Editing Invest</h1>

<%= render 'form' %>

<%= link_to 'Show', @invest %> |
<%= link_to 'Back', invests_path %>

app/views/invests/index.html.erb
<p id="notice"><%= notice %></p>

<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<%= javascript_include_tag "application" %>
<%= javascript_include_tag "zepto.min.js" %>


<h1>Listing Invests</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Bank</th>
      <th>Name</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invests.each do |invest| %>
      <tr>
        <td><% unless invest.user.nil? %><%= invest.user.name %><% else %>unknown<% end %></td>
        <td><%= invest.bank %></td>
        <td><%= invest.name %></td>
        <td><%= invest.amount %></td>
        <td><%= link_to 'Show', invest %></td>
        <td><%= link_to 'Edit', edit_invest_path(invest) %></td>
        <td><%= link_to 'Destroy', invest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invest', new_invest_path %>

app/views/invests/new.html.erb
<h1>New Invest</h1>

<%= render 'form' %>

<%= link_to 'Back', invests_path %>

app/views/invests/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>User:</strong>
  <% unless @invest.user.nil? %>
    <%= @invest.user.name %>
  <% else %>
    unknown user
  <% end %>
</p>

<p>
  <strong>Bank:</strong>
  <%= @invest.bank %>
</p>

<p>
  <strong>Name:</strong>
  <%= @invest.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @invest.amount %>
</p>

<p>
  <strong>Creation date:</strong>
  <%= @invest.created_at %>
</p>

<%= link_to 'Edit', edit_invest_path(@invest) %> |
<%= link_to 'Back', invests_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Admin', '/admin' %></li>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'Dashboard', page_path('dashboard') %></li>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Invest3" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Invest3" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <script src="http://code.highcharts.com/highcharts.js"></script>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/pages/dashboard.html.erb
<% content_for :title do %>Dashboard for <%= current_user.name %><% end %>

<!-- %= javascript_include_tag "//www.google.com/jsapi", "chartkick" % -->
<!-- %= javascript_include_tag "application" % -->
<!-- %= javascript_include_tag "zepto.min.js" % -->

<h3>Dashboard for <%= current_user.name %></h3>
<h1><a class="toogle-trigger">Amount chart</a></h1>
<div class="toogle-wrap" id="myGraph" style="display: none;">
Amount graphic should be here, contact site admin
</div>

<script>
$(document).ready(function() {
  $(".toogle-trigger").click(function() {
    $(this).parent().nextAll('.toogle-wrap').first().toggle('slow');
  });
    var url  =  "http://<%= request.env['SERVER_NAME'] %>:<%= request.env["SERVER_PORT"] %>/charts/glist/<%= current_user.id %>/year";
    var options = {
        chart: {
            //renderTo: "myGraph",
            //type: 'spline'
        },
        yAxis: {
            allowDecimals: true,
            title: {
                text: 'Amount'
            }
        },
        xAxis: {
            type: 'datetime',
            labels: {
                rotation: 45,
                align: 'left'
            },
        },
        rangeSelector: {
           buttons: [{
	           type: 'month',
	           count: 1,
	           text: '1m'
           }, {
	           type: 'month',
	           count: 3,
	           text: '3m'
           }, {
	           type: 'month',
	           count: 6,
	           text: '6m'
           }, {
	           type: 'ytd',
	           text: 'YTD'
           }, {
	           type: 'year',
	           count: 1,
	           text: '1y'
           }, {
	           type: 'all',
	           text: 'All'
           }],
           selected: 0,
        },
        title: {
            text: 'Amount over time'
        },
        series: []
    };
    //console.debug("renderTo: " + options.chart.renderTo);
    //var url =  "http://<%= request.env['REQUEST_URI'] %>/charts/glist/<%= current_user %>/week";
    $.getJSON(url,  function(data) {
       options.series = data;
       // var chart = new Highcharts.StockChart(options);
      $('#myGraph').highcharts('StockChart',options);
    });
});
</script>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>
<p>Token: <%= @user.auth_token if @user.auth_token %></p>

app/views/visitors/index.html.erb
<div id="wrapper">

    <!-- Sidebar -->
    <div id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <li class="sidebar-brand">
                <a href="#">
                    Start Bootstrap
                </a>
            </li>
            <li>
                <%= link_to "Invests",invests_path %>
            </li>
            <li>
                <a href="#">Dashboard</a>
            </li>
            <li>
                <a href="#">Shortcuts</a>
            </li>
            <li>
                <a href="#">Overview</a>
            </li>
            <li>
                <a href="#">Events</a>
            </li>
            <li>
                <a href="#">About</a>
            </li>
            <li>
                <a href="#">Services</a>
            </li>
            <li>
                <a href="#">Contact</a>
            </li>
        </ul>
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <h1>Simple Sidebar</h1>
                    <p>This template has a responsive menu toggling system. The menu will appear collapsed on smaller screens, and will appear non-collapsed on larger screens. When toggled using the button below, the menu will appear/disappear. On small screens, the page content will be pushed off canvas.</p>
                    <p>Make sure to keep all page content within the <code>#page-content-wrapper</code>.</p>
                    <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
                </div>
            </div>
        </div>
    </div>
    <!-- /#page-content-wrapper -->

</div>
<!-- /#wrapper -->

<!-- Menu Toggle Script -->
<script>
$("#menu-toggle").click(function(e) {
    e.preventDefault();
    $("#wrapper").toggleClass("toggled");
});
</script>